export const list = 'list'
export const standartTasks = 'standartTasks'
export const history = 'history'
export const loginUser = 'login'
export const logoutUser = 'logout'
export const companyLicenses = 'companyLicenses'
export const usersList = 'usersList'